apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: demo-model-prod
  namespace: dognauts-demo
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - env:
          - name: GUNICORN_WORKERS
            value: '2'
          - name: GUNICORN_THREADS
            value: '2'
          livenessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          name: demo-model-prod
          readinessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 1Gi
    graph:
      envSecretRefName: seldon-secret
      implementation: MLFLOW_SERVER
      modelUri: s3://dognauts-demo/1/eefbd7c1b9984ce8861d5acf3fdb31fb/artifacts/model
      name: demo-model-prod
    name: demo-model-prod
    replicas: 1
