apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: online-model-prod
  namespace: dognauts-backup
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - env:
          - name: GUNICORN_WORKERS
            value: '2'
          - name: GUNICORN_THREADS
            value: '2'
          livenessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          name: online-model
          readinessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 1Gi
    graph:
      envSecretRefName: seldon-secret
      implementation: MLFLOW_SERVER
      modelUri: s3://dognauts-backup/1/5a49c6224dfa403a9ecea8b72349e09e/artifacts/model
      name: online-model
    name: online-model
    replicas: 1
