apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: online-model-production
  namespace: dognauts-demo
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - env:
          - name: GUNICORN_WORKERS
            value: '2'
          - name: GUNICORN_THREADS
            value: '2'
          livenessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          name: online-model-production
          readinessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 2Gi
    graph:
      envSecretRefName: seldon-secret
      implementation: MLFLOW_SERVER
      modelUri: s3://dognauts-demo/1/e89e7276bfe6494489823895698aad66/artifacts/model
      name: online-model-production
    name: online-model-production
    replicas: 1
